name: innotech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/innotech_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat  
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
